### ISSUE TITLE
SVG Icon too blurry

### ISSUE THREAD

**Issue by MonstrousOgre** [ArtsyMacaw/wlogout#31]
I have this in my config
```
#logout {
    background-image: image(url("/usr/share/icons/Papirus-Dark/symbolic/actions/system-log-out-symbolic.svg"));
}
```

I'm using the default icons for all the other buttons. I end up getting a blurry image like this.

![image](https://user-images.githubusercontent.com/16362557/236609292-b0af77f3-70eb-4efb-9e1a-961aae54f04b.png)

The image appears crisp when I view it on Inkscape or my browser, even on bigger sizes.

**Comment by nabakdev** [comment]
facing the same issue. i copy svg files to `~/.configs/wlogout/icons/` and set `width` & `height`  svg attributes to `512` then the icons looks good now

```css
/* sample config */
#shutdown {
  background-image: image(
    url("./icons/shutdown.svg"),
    url("/usr/share/wlogout/icons/shutdown.png"),
    url("/usr/local/share/wlogout/icons/shutdown.png")
  );
}
```
![screenshot-2023-07-05-17:15:34](https://github.com/ArtsyMacaw/wlogout/assets/29066277/80cc4af2-983f-4643-b8cd-e3076b2dd782)
