### ISSUE TITLE
Customized icons are ok but only sometime

### ISSUE THREAD

**Issue by javier-fuentes** [ArtsyMacaw/wlogout#61]
- **Environment.** NixOS, LabWC (DE), foot (terminal), fish (shell)
- **Bug description.** Customized icons are not visible and red stripes are showed instead when *wlogout* is launched from terminal, but everything is fine when it's launched from a waybar's custom button

Customized SVG icons are stored in ```~/.config/wlogout/icons/``` and ```~/.config/wlogout/style.css``` has been modified accordingly:
```css
#lock      { background-image: image(url("./icons/lock.svg")) }
#logout    { background-image: image(url("./icons/logout.svg")) }
#suspend   { background-image: image(url("./icons/suspend.svg")) }
#hibernate { background-image: image(url("./icons/hibernate.svg")) }
#reboot    { background-image: image(url("./icons/reboot.svg")) }
#shutdown  { background-image: image(url("./icons/shutdown.svg")) }
```
Changing paths from relative ```./icons/...``` to absolute ```/home/...``` doesn't help

Nice tool by the way
